### About this demo

This demo shows the equivalence of `pennylane_encoding` and `qiskit_encoding` in main script, and the equivalence of `QCGNN_IX` and `QCGNN_H`.

In [1]:
from itertools import product
import os
import sys

import lightning as L
import torch

sys.path.append(os.path.abspath('../'))

from src.models import qcgnn

In [2]:
num_batch = 3
num_nr_qubits = 2 # Number of qubits in NR.
aggregation = 'MEAN'

def circuit(model, backend, num_ir_qubits):
    global num_nr_qubits

    return model(
        num_ir_qubits=num_ir_qubits,
        num_nr_qubits=num_nr_qubits,
        num_layers=1,
        num_reupload=1,
        qdevice='default.qubit',
        qbackend=backend,
        aggregation=aggregation,
    )

for rnd_seed, num_ir_qubits in product(range(3), range(1, 5)):
    L.seed_everything(rnd_seed) # For reproducing weights initialization.
    pennylane_circuit_IX = circuit(qcgnn.QCGNN_IX, 'pennylane', num_ir_qubits)
    
    L.seed_everything(rnd_seed) # For reproducing weights initialization.
    pennylane_circuit_0 = circuit(qcgnn.QCGNN_H, 'pennylane', num_ir_qubits)

    L.seed_everything(rnd_seed) # For reproducing weights initialization.
    qiskit_circuit_IX = circuit(qcgnn.QCGNN_IX, 'qiskit', num_ir_qubits)
    
    L.seed_everything(rnd_seed) # For reproducing weights initialization.
    qiskit_circuit_0 = circuit(qcgnn.QCGNN_H, 'qiskit', num_ir_qubits)

    num_ptcs = 2 ** num_ir_qubits
    x = torch.rand(num_batch, num_ptcs, 3)

    y_pennylane_IX = pennylane_circuit_IX(x)
    y_pennylane_0 = pennylane_circuit_0(x)
    y_qiskit_IX = qiskit_circuit_IX(x)
    y_qiskit_0 = qiskit_circuit_0(x)

    print()
    print(f"Result with `num_ptcs = {num_ptcs}` | `num_batch = {num_batch}` | `aggr = {aggregation}`:")
    print(f" - QCGNN_IX (PennyLane) ->\n{y_pennylane_IX}")
    print(f" - QCGNN_H (PennyLane)  ->\n{y_pennylane_0}")
    print(f" - QCGNN_IX (Qiskit)    ->\n{y_qiskit_IX}")
    print(f" - QCGNN_H (Qiskit)     ->\n{y_qiskit_0}")
    
    print(f"\n{'-'*100}\n")

Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
/home/yianchen/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pennylane/math/utils.py:227: UserWarning: Contains tensors of types {'autograd', 'torch'}; dispatch will prioritize TensorFlow, PyTorch, and  Jax over Autograd. Consider replacing Autograd with vanilla NumPy.
  warnings.warn(
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0


# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = qiskit
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = qiskit
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: **Warning** -> Using Hadamard initializaion.
# ModelLog: **Warning** -> Using Hadamard initializaion.
# ModelLog: **Warning** -> Using Hadamard initializaion.
# ModelLog: **Warning** -> Using Hadamard initializaion.

Result with `num_ptcs = 2` | `num_batch = 3` | `aggr = MEAN`:
 - QCGNN_IX (PennyLane) ->
tensor([[ 0.4504, -0.1941],
        [ 0.2593, -0.0482],
        [ 0.4517, -0.2090]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[ 0.4504, -0.1941],
    

Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0


# ModelLog: **Warning** -> Using Hadamard initializaion.
# ModelLog: **Warning** -> Using Hadamard initializaion.

Result with `num_ptcs = 8` | `num_batch = 3` | `aggr = MEAN`:
 - QCGNN_IX (PennyLane) ->
tensor([[ 0.3591, -0.1339],
        [ 0.3160, -0.1159],
        [ 0.3743, -0.1423]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[ 0.3591, -0.1339],
        [ 0.3160, -0.1159],
        [ 0.3743, -0.1423]], grad_fn=<DivBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[ 0.3591, -0.1339],
        [ 0.3160, -0.1159],
        [ 0.3743, -0.1423]], grad_fn=<DivBackward0>)
 - QCGNN_H (Qiskit)     ->
tensor([[ 0.3591, -0.1339],
        [ 0.3160, -0.1159],
        [ 0.3743, -0.1423]], grad_fn=<DivBackward0>)

----------------------------------------------------------------------------------------------------

# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((4, 0, 2))
# ModelLog: Quantum device  = default.qubit
# 

Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1



Result with `num_ptcs = 16` | `num_batch = 3` | `aggr = MEAN`:
 - QCGNN_IX (PennyLane) ->
tensor([[ 0.3369, -0.1226],
        [ 0.3231, -0.1350],
        [ 0.2462, -0.1244]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[ 0.3369, -0.1226],
        [ 0.3231, -0.1350],
        [ 0.2462, -0.1244]], grad_fn=<DivBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[ 0.3369, -0.1226],
        [ 0.3231, -0.1350],
        [ 0.2462, -0.1244]], grad_fn=<DivBackward0>)
 - QCGNN_H (Qiskit)     ->
tensor([[ 0.3369, -0.1226],
        [ 0.3231, -0.1350],
        [ 0.2462, -0.1244]], grad_fn=<DivBackward0>)

----------------------------------------------------------------------------------------------------

# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device  =

Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1


# ModelLog: **Warning** -> Using Hadamard initializaion.

Result with `num_ptcs = 8` | `num_batch = 3` | `aggr = MEAN`:
 - QCGNN_IX (PennyLane) ->
tensor([[-0.5320,  0.3766],
        [-0.4747,  0.3670],
        [-0.4734,  0.3730]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[-0.5320,  0.3766],
        [-0.4747,  0.3670],
        [-0.4734,  0.3730]], grad_fn=<DivBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[-0.5320,  0.3766],
        [-0.4747,  0.3670],
        [-0.4734,  0.3730]], grad_fn=<DivBackward0>)
 - QCGNN_H (Qiskit)     ->
tensor([[-0.5320,  0.3766],
        [-0.4747,  0.3670],
        [-0.4734,  0.3730]], grad_fn=<DivBackward0>)

----------------------------------------------------------------------------------------------------

# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((4, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits 

Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2


# ModelLog: **Warning** -> Using Hadamard initializaion.

Result with `num_ptcs = 16` | `num_batch = 3` | `aggr = MEAN`:
 - QCGNN_IX (PennyLane) ->
tensor([[-0.5028,  0.3716],
        [-0.4791,  0.3447],
        [-0.4880,  0.3897]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[-0.5028,  0.3716],
        [-0.4791,  0.3447],
        [-0.4880,  0.3897]], grad_fn=<DivBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[-0.5028,  0.3716],
        [-0.4791,  0.3447],
        [-0.4880,  0.3897]], grad_fn=<DivBackward0>)
 - QCGNN_H (Qiskit)     ->
tensor([[-0.5028,  0.3716],
        [-0.4791,  0.3447],
        [-0.4880,  0.3897]], grad_fn=<DivBackward0>)

----------------------------------------------------------------------------------------------------

# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits

Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2



Result with `num_ptcs = 4` | `num_batch = 3` | `aggr = MEAN`:
 - QCGNN_IX (PennyLane) ->
tensor([[-0.4598, -0.0591],
        [-0.5206, -0.0897],
        [-0.6257, -0.2379]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[-0.4598, -0.0591],
        [-0.5206, -0.0897],
        [-0.6257, -0.2379]], grad_fn=<DivBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[-0.4598, -0.0591],
        [-0.5206, -0.0897],
        [-0.6257, -0.2379]], grad_fn=<DivBackward0>)
 - QCGNN_H (Qiskit)     ->
tensor([[-0.4598, -0.0591],
        [-0.5206, -0.0897],
        [-0.6257, -0.2379]], grad_fn=<DivBackward0>)

----------------------------------------------------------------------------------------------------

# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((3, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((3, 0, 2))
# ModelLog: Quantum device  = 