### About this demo

This demo shows the equivalence of `pennylane_encoding` and `qiskit_encoding` in main script, and the equivalence of `QCGNN_IX` and `QCGNN_H`.

In [1]:
from itertools import product
import os
import sys

import lightning as L
import pennylane as qml
import torch

sys.path.append(os.path.abspath('../'))

from source.models import qcgnn

In [2]:
num_batch = 3
num_nr_qubits = 2
num_rotation = 3
vqc_ansatz = qml.StronglyEntanglingLayers
aggregation = 'mean'

def circuit(model, backend, num_ir_qubits):
    global num_nr_qubits

    return model(
        num_ir_qubits=num_ir_qubits,
        num_nr_qubits=num_nr_qubits,
        num_layers=1,
        num_reupload=1,
        num_rotation=num_rotation,
        vqc_ansatz=vqc_ansatz,
        qdevice='default.qubit',
        qbackend=backend,
        aggregation=aggregation,
    )

for rnd_seed, num_ir_qubits in product(range(3), range(1, 5)):
    L.seed_everything(rnd_seed) # For reproducing weights initialization.
    pennylane_circuit_IX = circuit(qcgnn.QCGNN_IX, 'pennylane', num_ir_qubits)
    
    L.seed_everything(rnd_seed) # For reproducing weights initialization.
    pennylane_circuit_0 = circuit(qcgnn.QCGNN_H, 'pennylane', num_ir_qubits)

    L.seed_everything(rnd_seed) # For reproducing weights initialization.
    qiskit_circuit_IX = circuit(qcgnn.QCGNN_IX, 'qiskit', num_ir_qubits)
    
    L.seed_everything(rnd_seed) # For reproducing weights initialization.
    qiskit_circuit_0 = circuit(qcgnn.QCGNN_H, 'qiskit', num_ir_qubits)

    num_ptcs = 2 ** num_ir_qubits
    x = torch.rand(num_batch, num_ptcs, num_rotation * num_nr_qubits)

    y_pennylane_IX = pennylane_circuit_IX(x)
    y_pennylane_0 = pennylane_circuit_0(x)
    y_qiskit_IX = qiskit_circuit_IX(x)
    y_qiskit_0 = qiskit_circuit_0(x)

    print()
    print(f"Result with `num_ptcs = {num_ptcs}` | `num_batch = {num_batch}` | `aggr = {aggregation}`:")
    print(f" - QCGNN_IX (PennyLane) ->\n{y_pennylane_IX}")
    print(f" - QCGNN_H (PennyLane)  ->\n{y_pennylane_0}")
    print(f" - QCGNN_IX (Qiskit)    ->\n{y_qiskit_IX}")
    print(f" - QCGNN_H (Qiskit)     ->\n{y_qiskit_0}")
    
    print(f"\n{'-'*100}\n")

Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
/home/yianchen/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pennylane/math/utils.py:227: UserWarning: Contains tensors of types {'torch', 'autograd'}; dispatch will prioritize TensorFlow, PyTorch, and  Jax over Autograd. Consider replacing Autograd with vanilla NumPy.
  warnings.warn(
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0



Result with `num_ptcs = 2` | `num_batch = 3` | `aggr = mean`:
 - QCGNN_IX (PennyLane) ->
tensor([[-0.8739,  0.3722],
        [-0.7626,  0.5684],
        [-0.7860,  0.3346]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[-0.8739,  0.3722],
        [-0.7626,  0.5684],
        [-0.7860,  0.3346]], grad_fn=<DivBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[-0.8739,  0.3722],
        [-0.7626,  0.5684],
        [-0.7860,  0.3346]], grad_fn=<DivBackward0>)
 - QCGNN_H (Qiskit)     ->
tensor([[-0.8739,  0.3722],
        [-0.7626,  0.5684],
        [-0.7860,  0.3346]], grad_fn=<DivBackward0>)

----------------------------------------------------------------------------------------------------


Result with `num_ptcs = 4` | `num_batch = 3` | `aggr = mean`:
 - QCGNN_IX (PennyLane) ->
tensor([[-0.8066,  0.4823],
        [-0.8384,  0.4667],
        [-0.8231,  0.6996]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[-0.8066,  0.4823],
        [-0.8384,  0.4667],
        

Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0



Result with `num_ptcs = 8` | `num_batch = 3` | `aggr = mean`:
 - QCGNN_IX (PennyLane) ->
tensor([[-0.8219,  0.4719],
        [-0.8482,  0.6900],
        [-0.8292,  0.5749]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[-0.8219,  0.4719],
        [-0.8482,  0.6900],
        [-0.8292,  0.5749]], grad_fn=<DivBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[-0.8219,  0.4719],
        [-0.8482,  0.6900],
        [-0.8292,  0.5749]], grad_fn=<DivBackward0>)
 - QCGNN_H (Qiskit)     ->
tensor([[-0.8219,  0.4719],
        [-0.8482,  0.6900],
        [-0.8292,  0.5749]], grad_fn=<DivBackward0>)

----------------------------------------------------------------------------------------------------



Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1



Result with `num_ptcs = 16` | `num_batch = 3` | `aggr = mean`:
 - QCGNN_IX (PennyLane) ->
tensor([[-0.8288,  0.5839],
        [-0.8549,  0.5276],
        [-0.8317,  0.5628]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[-0.8288,  0.5839],
        [-0.8549,  0.5276],
        [-0.8317,  0.5628]], grad_fn=<DivBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[-0.8288,  0.5839],
        [-0.8549,  0.5276],
        [-0.8317,  0.5628]], grad_fn=<DivBackward0>)
 - QCGNN_H (Qiskit)     ->
tensor([[-0.8288,  0.5839],
        [-0.8549,  0.5276],
        [-0.8317,  0.5628]], grad_fn=<DivBackward0>)

----------------------------------------------------------------------------------------------------


Result with `num_ptcs = 2` | `num_batch = 3` | `aggr = mean`:
 - QCGNN_IX (PennyLane) ->
tensor([[0.5271, 0.1706],
        [0.4876, 0.1482],
        [0.7924, 0.3661]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[0.5271, 0.1706],
        [0.4876, 0.1482],
        [0.7924, 

Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1



Result with `num_ptcs = 8` | `num_batch = 3` | `aggr = mean`:
 - QCGNN_IX (PennyLane) ->
tensor([[0.5675, 0.2039],
        [0.4748, 0.1623],
        [0.3824, 0.1325]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[0.5675, 0.2039],
        [0.4748, 0.1623],
        [0.3824, 0.1325]], grad_fn=<DivBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[0.5675, 0.2039],
        [0.4748, 0.1623],
        [0.3824, 0.1325]], grad_fn=<DivBackward0>)
 - QCGNN_H (Qiskit)     ->
tensor([[0.5675, 0.2039],
        [0.4748, 0.1623],
        [0.3824, 0.1325]], grad_fn=<DivBackward0>)

----------------------------------------------------------------------------------------------------



Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2



Result with `num_ptcs = 16` | `num_batch = 3` | `aggr = mean`:
 - QCGNN_IX (PennyLane) ->
tensor([[0.5208, 0.1842],
        [0.4244, 0.1484],
        [0.3576, 0.0852]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[0.5208, 0.1842],
        [0.4244, 0.1484],
        [0.3576, 0.0852]], grad_fn=<DivBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[0.5208, 0.1842],
        [0.4244, 0.1484],
        [0.3576, 0.0852]], grad_fn=<DivBackward0>)
 - QCGNN_H (Qiskit)     ->
tensor([[0.5208, 0.1842],
        [0.4244, 0.1484],
        [0.3576, 0.0852]], grad_fn=<DivBackward0>)

----------------------------------------------------------------------------------------------------


Result with `num_ptcs = 2` | `num_batch = 3` | `aggr = mean`:
 - QCGNN_IX (PennyLane) ->
tensor([[-0.5949, -0.1370],
        [-0.7226, -0.1068],
        [-0.6581,  0.0070]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[-0.5949, -0.1370],
        [-0.7226, -0.1068],
        [-0.6581,  0.0070]], gr

Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2



Result with `num_ptcs = 8` | `num_batch = 3` | `aggr = mean`:
 - QCGNN_IX (PennyLane) ->
tensor([[-0.6834, -0.1699],
        [-0.7932, -0.1149],
        [-0.7147, -0.0897]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[-0.6834, -0.1699],
        [-0.7932, -0.1149],
        [-0.7147, -0.0897]], grad_fn=<DivBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[-0.6834, -0.1699],
        [-0.7932, -0.1149],
        [-0.7147, -0.0897]], grad_fn=<DivBackward0>)
 - QCGNN_H (Qiskit)     ->
tensor([[-0.6834, -0.1699],
        [-0.7932, -0.1149],
        [-0.7147, -0.0897]], grad_fn=<DivBackward0>)

----------------------------------------------------------------------------------------------------


Result with `num_ptcs = 16` | `num_batch = 3` | `aggr = mean`:
 - QCGNN_IX (PennyLane) ->
tensor([[-0.7380, -0.1419],
        [-0.7166, -0.0704],
        [-0.6999, -0.1633]], grad_fn=<DivBackward0>)
 - QCGNN_H (PennyLane)  ->
tensor([[-0.7380, -0.1419],
        [-0.7166, -0.0704],
       