### About this demo

This demo shows the equivalence of `pennylane_encoding` and `qiskit_encoding` in main script, and the equivalence of `QCGNN_IX` and `QCGNN_H`.

In [1]:
from itertools import product
import os
import sys

import lightning as L
import torch

sys.path.append(os.path.abspath('../'))

from source.models import qcgnn

In [2]:
num_batch = 3
num_nr_qubits = 2 # Number of qubits in NR.
aggregation = 'MEAN'

def circuit(model, backend, num_ir_qubits):
    global num_nr_qubits

    return model(
        num_ir_qubits=num_ir_qubits,
        num_nr_qubits=num_nr_qubits,
        num_layers=1,
        num_reupload=1,
        qdevice='default.qubit',
        qbackend=backend,
        aggregation=aggregation,
    )

for rnd_seed, num_ir_qubits in product(range(3), range(1, 5)):
    L.seed_everything(rnd_seed) # For reproducing weights initialization.
    pennylane_circuit_IX = circuit(qcgnn.QCGNN_IX, 'pennylane', num_ir_qubits)
    
    L.seed_everything(rnd_seed) # For reproducing weights initialization.
    pennylane_circuit_0 = circuit(qcgnn.QCGNN_H, 'pennylane', num_ir_qubits)

    L.seed_everything(rnd_seed) # For reproducing weights initialization.
    qiskit_circuit_IX = circuit(qcgnn.QCGNN_IX, 'qiskit', num_ir_qubits)
    
    L.seed_everything(rnd_seed) # For reproducing weights initialization.
    qiskit_circuit_0 = circuit(qcgnn.QCGNN_H, 'qiskit', num_ir_qubits)

    num_ptcs = 2 ** num_ir_qubits
    x = torch.rand(num_batch, num_ptcs, 3)

    y_pennylane_IX = pennylane_circuit_IX(x)
    y_pennylane_0 = pennylane_circuit_0(x)
    y_qiskit_IX = qiskit_circuit_IX(x)
    y_qiskit_0 = qiskit_circuit_0(x)

    print()
    print(f"Result with `num_ptcs = {num_ptcs}` | `num_batch = {num_batch}` | `aggr = {aggregation}`:")
    print(f" - QCGNN_IX (PennyLane) ->\n{y_pennylane_IX}")
    print(f" - QCGNN_H (PennyLane)  ->\n{y_pennylane_0}")
    print(f" - QCGNN_IX (Qiskit)    ->\n{y_qiskit_IX}")
    print(f" - QCGNN_H (Qiskit)     ->\n{y_qiskit_0}")
    
    print(f"\n{'-'*100}\n")

Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
/home/yianchen/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pennylane/math/utils.py:227: UserWarning: Contains tensors of types {'autograd', 'torch'}; dispatch will prioritize TensorFlow, PyTorch, and  Jax over Autograd. Consider replacing Autograd with vanilla NumPy.
  warnings.warn(
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0


# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = qiskit
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = qiskit
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))

Result with `num_ptcs = 2` | `num_batch = 3` | `aggr = MEAN`:
 - QCGNN_IX (PennyLane) ->
tensor([[ 0.9008, -0.3882],
        [ 0.5185, -0.0963],
        [ 0.9033, -0.4181]], grad_fn=<SumBackward1>)
 - QCGNN_H (PennyLane)  ->
tensor([[ 0.9008, -0.3882],
        [ 0.5185, -0.0963],
        [ 0.9033, -0.4181]], grad_fn=<ViewBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[ 0.9008, -0.3882],
        [ 0.5185, -0.0963],
        [ 0.9033, -0.4181]], grad_fn=<SumBackward1>)
 - QCGNN_H (Qi

Seed set to 0
Seed set to 0
Seed set to 0
Seed set to 0



Result with `num_ptcs = 8` | `num_batch = 3` | `aggr = MEAN`:
 - QCGNN_IX (PennyLane) ->
tensor([[ 2.8729, -1.0713],
        [ 2.5282, -0.9276],
        [ 2.9941, -1.1384]], grad_fn=<SumBackward1>)
 - QCGNN_H (PennyLane)  ->
tensor([[ 2.8729, -1.0713],
        [ 2.5282, -0.9276],
        [ 2.9941, -1.1384]], grad_fn=<ViewBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[ 2.8729, -1.0713],
        [ 2.5282, -0.9276],
        [ 2.9941, -1.1384]], grad_fn=<SumBackward1>)
 - QCGNN_H (Qiskit)     ->
tensor([[ 2.8729, -1.0713],
        [ 2.5282, -0.9276],
        [ 2.9941, -1.1384]], grad_fn=<ViewBackward0>)

----------------------------------------------------------------------------------------------------

# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((4, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((4, 0, 2))
# ModelLog: Quantum device  

Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1



Result with `num_ptcs = 16` | `num_batch = 3` | `aggr = MEAN`:
 - QCGNN_IX (PennyLane) ->
tensor([[ 5.3903, -1.9610],
        [ 5.1696, -2.1593],
        [ 3.9397, -1.9906]], grad_fn=<SumBackward1>)
 - QCGNN_H (PennyLane)  ->
tensor([[ 5.3903, -1.9610],
        [ 5.1696, -2.1593],
        [ 3.9397, -1.9906]], grad_fn=<ViewBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[ 5.3903, -1.9610],
        [ 5.1696, -2.1593],
        [ 3.9397, -1.9906]], grad_fn=<SumBackward1>)
 - QCGNN_H (Qiskit)     ->
tensor([[ 5.3903, -1.9610],
        [ 5.1696, -2.1593],
        [ 3.9397, -1.9906]], grad_fn=<ViewBackward0>)

----------------------------------------------------------------------------------------------------

# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device 

Seed set to 1
Seed set to 1
Seed set to 1
Seed set to 1



Result with `num_ptcs = 8` | `num_batch = 3` | `aggr = MEAN`:
 - QCGNN_IX (PennyLane) ->
tensor([[-4.2560,  3.0128],
        [-3.7977,  2.9363],
        [-3.7875,  2.9840]], grad_fn=<SumBackward1>)
 - QCGNN_H (PennyLane)  ->
tensor([[-4.2560,  3.0128],
        [-3.7977,  2.9363],
        [-3.7875,  2.9840]], grad_fn=<ViewBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[-4.2560,  3.0128],
        [-3.7977,  2.9363],
        [-3.7875,  2.9840]], grad_fn=<SumBackward1>)
 - QCGNN_H (Qiskit)     ->
tensor([[-4.2560,  3.0128],
        [-3.7977,  2.9363],
        [-3.7875,  2.9840]], grad_fn=<ViewBackward0>)

----------------------------------------------------------------------------------------------------

# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((4, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((4, 0, 2))
# ModelLog: Quantum device  

Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2



Result with `num_ptcs = 16` | `num_batch = 3` | `aggr = MEAN`:
 - QCGNN_IX (PennyLane) ->
tensor([[-8.0441,  5.9456],
        [-7.6662,  5.5153],
        [-7.8075,  6.2348]], grad_fn=<SumBackward1>)
 - QCGNN_H (PennyLane)  ->
tensor([[-8.0441,  5.9456],
        [-7.6662,  5.5153],
        [-7.8075,  6.2348]], grad_fn=<ViewBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[-8.0441,  5.9456],
        [-7.6662,  5.5153],
        [-7.8075,  6.2348]], grad_fn=<SumBackward1>)
 - QCGNN_H (Qiskit)     ->
tensor([[-8.0441,  5.9456],
        [-7.6662,  5.5153],
        [-7.8075,  6.2348]], grad_fn=<ViewBackward0>)

----------------------------------------------------------------------------------------------------

# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((1, 0, 2))
# ModelLog: Quantum device 

Seed set to 2
Seed set to 2
Seed set to 2
Seed set to 2



Result with `num_ptcs = 8` | `num_batch = 3` | `aggr = MEAN`:
 - QCGNN_IX (PennyLane) ->
tensor([[-3.9179, -0.5968],
        [-2.8602, -0.9338],
        [-2.9498, -1.1109]], grad_fn=<SumBackward1>)
 - QCGNN_H (PennyLane)  ->
tensor([[-3.9179, -0.5968],
        [-2.8602, -0.9338],
        [-2.9498, -1.1109]], grad_fn=<ViewBackward0>)
 - QCGNN_IX (Qiskit)    ->
tensor([[-3.9179, -0.5968],
        [-2.8602, -0.9338],
        [-2.9498, -1.1109]], grad_fn=<SumBackward1>)
 - QCGNN_H (Qiskit)     ->
tensor([[-3.9179, -0.5968],
        [-2.8602, -0.9338],
        [-2.9498, -1.1109]], grad_fn=<ViewBackward0>)

----------------------------------------------------------------------------------------------------

# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((4, 0, 2))
# ModelLog: Quantum device  = default.qubit
# ModelLog: Quantum backend = pennylane
# ModelLog: Qubits (IR, WK, NR) = ((4, 0, 2))
# ModelLog: Quantum device  